# GitLab CI pipeline for tmdb-devops-challenge
# Branch: devops-ci-solution
# Cloud target: Azure (ACR)

stages:
  - lint
  - test
  - build
  - docker_build  
  - cloud_push
# --------------------
# LINT STAGE
# --------------------
lint:
  stage: lint
  image: node:18-alpine
  script:
    - npm ci
    - npm run lint
  only:
    - devops-ci-solution

# --------------------
# TEST STAGE
# --------------------
test:
  stage: test
  image: node:18-alpine
  script:
    - npm ci
    - npm test -- --watchAll=false
  only:
    - devops-ci-solution

# --------------------
# BUILD STAGE
# --------------------
build:
  stage: build
  image: node:18-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - devops-ci-solution

# --------------------
# DOCKER BUILD STAGE
# -----------

docker_build:
  stage: docker_build
  image: docker:24
  services:
    - docker:dind
  script:
    - docker build -t tmdb-app-local .
    # Save the image to a file so the next stage can use it
    - docker save tmdb-app-local > tmdb-app.tar
  artifacts:
    paths:
      - tmdb-app.tar
    expire_in: 1 hr
  only:
    - devops-ci-solution

# --------------------
# THE PUSH STAGE (Uploads to Cloud)
# -----------

cloud_push:
  stage: cloud_push
  image: docker:24
  services:
    - docker:dind
  script:
    # Load the image we saved in the previous stage
    - docker load < tmdb-app.tar
    # Login and Push
    - docker login $CLOUD_REGISTRY -u "$CLOUD_USER" -p "$CLOUD_PASS"
    - docker tag tmdb-app-local $CLOUD_REGISTRY/tmdb-app:latest
    - docker push $CLOUD_REGISTRY/tmdb-app:latest
  only:
    - devops-ci-solution