# GitLab CI pipeline for tmdb-devops-challenge
# Branch: devops-ci-solution
# Cloud target: Azure (ACR)

stages:
  - lint
  - test
  - build
  - docker_build  
  - cloud_push
# --------------------
# LINT STAGE
# --------------------
lint:
  stage: lint
  image: node:18-alpine
  script:
    - npm ci
    - npm run lint
  only:
    - devops-ci-solution

# --------------------
# TEST STAGE
# --------------------
test:
  stage: test
  image: node:18-alpine
  script:
    - npm ci
    - npm test -- --watchAll=false
  only:
    - devops-ci-solution

# --------------------
# BUILD STAGE
# --------------------
build:
  stage: build
  image: node:18-alpine
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/
  only:
    - devops-ci-solution

# --------------------
# DOCKER BUILD STAGE
# -----------

docker_build:
  stage: docker_build
  image: docker:28.0
  services:
    - docker:28.0-dind
  script:
    - docker build -t tmdb-app-local .
    # Save the image to a file so the next stage can use it
    - docker save tmdb-app-local > tmdb-app.tar
  artifacts:
    paths:
      - tmdb-app.tar
    expire_in: 1 hr
  only:
    - devops-ci-solution

# --------------------
# THE PUSH STAGE (Uploads to Cloud)
# -----------

cloud_push:
  stage: cloud_push
  image: docker:28.0
  services:
    - name: docker:28.0-dind
  script:
    # 1. Load the image from the artifact
    - docker load < tmdb-app.tar
    
    # 2. Login using your Azure credentials
    - echo "$REGISTRY_PASSWORD" | docker login $REGISTRY_URL -u "$REGISTRY_USER" --password-stdin
    
    # 3. Tag with the unique Commit SHA (for traceability/rollbacks)
    - docker tag tmdb-app-local $REGISTRY_URL/tmdb-app:$CI_COMMIT_SHORT_SHA
    
    # 4. Tag as 'latest' (for the main deployment)
    - docker tag tmdb-app-local $REGISTRY_URL/tmdb-app:latest
    
    # 5. Push both tags
    - docker push $REGISTRY_URL/tmdb-app:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY_URL/tmdb-app:latest
    
    - echo "Successfully pushed to $REGISTRY_URL"
  only:
    - devops-ci-solution