# --------------------
# 4. DOCKER BUILD
# --------------------
docker_build:
  stage: docker_build
  # Full 64-char SHA for docker:28.0
  image: docker:28.0@sha256:73289069632890f55734e067c29574d6f8f53702a63251c5f3775b84260a9f5d
  services:
    - name: docker:28.0-dind@sha256:4de6a5668da5d138bf9c18b29d2702e43c8773daee085087ba4fac61a6d34b7f
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t tmdb-app-local .
    - docker save tmdb-app-local > tmdb-app.tar
  artifacts:
    paths:
      - tmdb-app.tar
    expire_in: 1 hr
  only:
    - devops-ci-solution

# --------------------
# 5. CLOUD PUSH
# --------------------
cloud_push:
  stage: cloud_push
  image: docker:28.0@sha256:73289069632890f55734e067c29574d6f8f53702a63251c5f3775b84260a9f5d
  services:
    - name: docker:28.0-dind@sha256:4de6a5668da5d138bf9c18b29d2702e43c8773daee085087ba4fac61a6d34b7f
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker load < tmdb-app.tar
    - echo "$REGISTRY_PASSWORD" | docker login $REGISTRY_URL -u "$REGISTRY_USER" --password-stdin
    - docker tag tmdb-app-local $REGISTRY_URL/tmdb-app:$CI_COMMIT_SHORT_SHA
    - docker tag tmdb-app-local $REGISTRY_URL/tmdb-app:latest
    - docker push $REGISTRY_URL/tmdb-app:$CI_COMMIT_SHORT_SHA
    - docker push $REGISTRY_URL/tmdb-app:latest
  only:
    - devops-ci-solution